services:
  wedding-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wedding-invitation
    ports:
      - "3333:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      # Mount the SQLite database file as a volume to persist data
      - ./wedding.db:/app/wedding.db
    restart: unless-stopped
    # Add healthcheck to ensure the container is running properly
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
